#include "cli/Usage.h"

#include <ostream>

namespace vmsourceconv::cli {

void PrintUsage(std::ostream& output) {
    output
        << "VMSourceCONV - Source 2 to Source 1 conversion toolkit\n\n"
        << "Usage:\n"
        << "  VMSourceCONV inspect <resource_c> [options]\n"
        << "  VMSourceCONV verify-vpk <package_dir.vpk> [options]\n\n"
        << "Inspect foundation options:\n"
        << "  --resource-root <dir>       Add a normal loose content root.\n"
        << "  --override-root <dir>       Add a highest-priority loose override root.\n"
        << "  --vpk <file-or-dir>         Add an explicit high-priority VPK package.\n"
        << "  --follow-references         Traverse structural dependencies.\n"
        << "  --include-assets            Follow all resource references.\n"
        << "  --report-vpk-collisions     Report shadowed exact VPK matches.\n"
        << "  --strict-vpk-collisions     Treat VPK collisions as errors.\n"
        << "  --no-vpk-crc                Disable VPK CRC checks for debugging.\n"
        << "  --max-depth <count>         Dependency depth limit (default: 4).\n"
        << "  --max-resources <count>     Resource count limit (default: 512).\n"
        << "  --max-input-bytes <bytes>   Maximum loose input allocation.\n"
        << "  --max-vpk-entry-bytes <n>   Maximum VPK entry allocation.\n"
        << "  --max-graph-bytes <bytes>   Maximum cumulative graph bytes.\n"
        << "  --no-rerl                   Do not decode external references.\n"
        << "  --strict                    Fail when warnings are present.\n\n"
        << "Inspect semantic/output options:\n"
        << "  --json <file>               Write the inspection report as JSON.\n"
        << "  --dump-blocks <dir>         Dump every valid root-resource block.\n"
        << "  --inspect-data              Classify DATA blocks.\n"
        << "  --decode-kv3                Decode Binary KV3 v5 documents.\n"
        << "  --entities-json <file>      Export decoded entity lumps.\n"
        << "  --kv3-json-dir <dir>        Export selected decoded KV3 documents.\n"
        << "  --kv3-filter <text>         Repeatable logical-name filter.\n"
        << "  --scene-json <file>         Export reconstructed world scenes.\n\n"
        << "verify-vpk options:\n"
        << "  --json <file>               Write the verification report as JSON.\n"
        << "  --no-vpk-crc                Skip entry CRC verification.\n"
        << "  --no-orphan-scan            Do not scan adjacent orphan chunks.\n"
        << "  --max-vpk-entry-bytes <n>   Maximum entry size checked.\n\n"
        << "Shared logging options:\n"
        << "  --log <file>, --log=<file>  Duplicate output and errors to a log.\n"
        << "  --name.txt                  Final-argument shorthand for --log.\n"
        << "  --log-mode overwrite|append\n"
        << "  --quiet                     Suppress normal terminal output.\n"
        << "  --verbose                   Enable verbose command reporting.\n"
        << "  --debug                     Enable debug command reporting.\n"
        << "  --no-log-timestamps         Omit timestamps from copied lines.\n"
        << "  -h, --help                  Show this help.\n"
        << "  -v, --version               Show the program version.\n\n"
        << "Resource lookup order:\n"
        << "  1. --override-root loose files.\n"
        << "  2. Explicit --vpk packages.\n"
        << "  3. A package matching the input map name.\n"
        << "  4. Normal loose roots.\n"
        << "  5. Recursive ./vpk fallback packages, pak01_dir.vpk first.\n\n"
        << "Examples:\n"
        << "  VMSourceCONV verify-vpk D:\\VMAT\\vpk\\pak01_dir.vpk --verify.txt\n"
        << "  VMSourceCONV inspect de_cache.vmap_c --follow-references "
           "--report-vpk-collisions --foundation.txt\n";
}

} // namespace vmsourceconv::cli
